### ISSUE TITLE
Control "next" is active, but elements are all visible

### ISSUE THREAD

**Issue by marvinschroeder** [jsor/jcarousel#559]
I have used the control Plugin and defined my CSS for the jCarousel like this:

``` css
.im-gallery-carousel-container {
    position: relative;
    overflow: hidden;
    height: 75px;    
}

.im-gallery-carousel-container ul {
    width: 20000em;
    position: absolute;
    list-style: none;
    margin: 0;
    padding: 0;
}

.im-gallery-carousel-container li {
    float: left;    
    width: 75px;
    margin: 0 5px;
}
```

``` javascript
$(".im-gallery-carousel-container").on('create.jcarousel', function(event, carousel) {            

    $(this).append('<div class="jcarousel-prev"></div><div class="jcarousel-next"></div>');

    $('.jcarousel-prev').on('active.jcarouselcontrol', function() {
    $(this).addClass('active');
    }).on('inactive.jcarouselcontrol', function() {
    $(this).removeClass('active');
    }).jcarouselControl({
    target: '-=1'
    });

    $('.jcarousel-next').on('active.jcarouselcontrol', function() {
    $(this).addClass('active');
    }).on('inactive.jcarouselcontrol', function() {
    $(this).removeClass('active');
    }).jcarouselControl({
    target: '+=1'
    });
}).jcarousel({
    vertical: false         
});
```

Unexpectenly the jCarousel always says the "next" button is active with only 3 li-items and a width of 100% / 590px at the container. But there is enough space: 3 x 75 (width of li) + 3 x 10 (margin of li) = 255px!
If i click on the button the "active" state disappears but nothing in the carousel itself changes.
Am i doing something wrong?
