### ISSUE TITLE
Pagination alignment

### ISSUE THREAD

**Issue by stevespeirs** [jsor/jcarousel#795]
Not really an issue, but trying to center align the pagination on the Basic Carousel. Any chance of some help with the css?

.jcarousel-pagination {
    position: absolute;
    bottom: 20px;
    margin: 0 auto;
}

**Comment by jsor** [comment]
There are several ways to do it. From the top of my head i'd use something like:

```css
.jcarousel-pagination {
    position: absolute;
    bottom: 20px;
    text-align: center;
    width: 100%;
}

.jcarousel-pagination li {
    display: inline-block;
    position: relative;
    /* ... */
}
```
